.TH mcacc 1 "12 September 2016" "version 3.1+"
.SH NAME
mcacc - mark carters accounts
.SH SYNOPSIS
.B mcacc
[OPTION] ...
.SH DESCRIPTION
Creates a set of accounts
.SH OPTIONS
.B
-h [ --help ]         Help
  --pre arg             Preprocess command
  --root                Print root directory
  --version             Version
  --clean               Clean up the working folders
  -s [ --snap ]         Snapshot

.SH RC FILE

Typical contents of mcacc.ini: pre="$REDACT/docs/accts2016/data/derive"


